(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const DEFAULTS={pattern:'sash',scale:100,base:'#f4f1e8',secondary:'#173f35',accent:'#c7f343',name:'NAKAMURA',nameSize:65,number:'10',font:'Impact',numberStyle:'solid',numberSize:100,nameX:0,nameY:22,numberX:0,numberY:40,logos:[],activeLogoId:null,autoRotate:false};
  let state={...DEFAULTS}, renderPending=false, toastTimer, scene,camera,renderer,uniformTexture,jersey,torso,sleeves=[],drag=false,lastX=0,lastY=0,targetRotY=.12,targetRotX=0,cameraZ=12;
  const logoImages=new Map();
  let arStream=null,arPose=null,arRunning=false,arBusy=false,arTimer=null,lastPoseLandmarks=null,arFacing='user';
  const patternNames={solid:'SOLID',stripes:'STRIPES',hoops:'HOOPS',sash:'SASH',gradient:'GRADIENT',waves:'WAVES',check:'CHECK',chevron:'CHEVRON',halftone:'HALFTONE',diagonal:'DIAGONAL',split:'SPLIT',lightning:'LIGHTNING',flame:'FLAME',topo:'TOPO',shards:'SHARDS',pulse:'PULSE',camo:'CAMO',orbit:'ORBIT'};
  const palettes=[['#f4f1e8','#173f35','#c7f343'],['#f8f5ef','#194ea0','#ef4c45'],['#101722','#35a8e0','#f7d64a'],['#fff','#7b1833','#e5b74f'],['#161616','#ececec','#ff4e42'],['#f1ede2','#5a2d82','#fead37']];
  const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=1024;const tctx=textureCanvas.getContext('2d');
  const patternCanvas=document.createElement('canvas');patternCanvas.width=512;patternCanvas.height=1024;const pctx=patternCanvas.getContext('2d');

  function drawPattern(ctx,w,h,type,base,second,accent,scale=1){
    ctx.fillStyle=base;ctx.fillRect(0,0,w,h);const s=Math.max(.35,scale);
    if(type==='solid')return;
    if(type==='stripes'){ctx.fillStyle=second;for(let x=-w;x<w*2;x+=w*.18*s)ctx.fillRect(x,0,w*.075*s,h);ctx.fillStyle=accent;for(let x=-w;x<w*2;x+=w*.36*s)ctx.fillRect(x+w*.075*s,0,w*.016*s,h)}
    if(type==='hoops'){ctx.fillStyle=second;for(let y=0;y<h;y+=h*.18*s)ctx.fillRect(0,y,w,h*.075*s);ctx.fillStyle=accent;for(let y=h*.075*s;y<h;y+=h*.36*s)ctx.fillRect(0,y,w,h*.014*s)}
    if(type==='sash'||type==='diagonal'){ctx.save();ctx.translate(w/2,h/2);ctx.rotate(type==='sash'?-.52:.52);ctx.fillStyle=second;ctx.fillRect(-w*1.4,-h*.12*s,w*2.8,h*.24*s);ctx.fillStyle=accent;ctx.fillRect(-w*1.4,h*.12*s,w*2.8,h*.035*s);ctx.restore()}
    if(type==='gradient'){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,base);g.addColorStop(.55,second);g.addColorStop(1,accent);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
    if(type==='waves'){ctx.strokeStyle=second;ctx.lineWidth=28*s;for(let y=30;y<h+60;y+=80*s){ctx.beginPath();for(let x=-30;x<w+30;x+=8)ctx.lineTo(x,y+Math.sin(x/(45*s))*22*s);ctx.stroke()}ctx.strokeStyle=accent;ctx.lineWidth=5*s;for(let y=65;y<h;y+=160*s){ctx.beginPath();for(let x=0;x<w;x+=8)ctx.lineTo(x,y+Math.sin(x/(45*s))*22*s);ctx.stroke()}}
    if(type==='check'){const z=110*s;for(let y=0;y<h;y+=z)for(let x=0;x<w;x+=z){ctx.fillStyle=((x/z+y/z)%2===0)?second:base;ctx.fillRect(x,y,z,z)}ctx.strokeStyle=accent;ctx.lineWidth=6;for(let x=0;x<w;x+=z)ctx.strokeRect(x,0,z,h)}
    if(type==='chevron'){ctx.strokeStyle=second;ctx.lineWidth=45*s;for(let y=-80;y<h+100;y+=120*s){ctx.beginPath();ctx.moveTo(-20,y);ctx.lineTo(w/2,y+100*s);ctx.lineTo(w+20,y);ctx.stroke()}ctx.strokeStyle=accent;ctx.lineWidth=7*s;for(let y=-20;y<h;y+=240*s){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w/2,y+100*s);ctx.lineTo(w,y);ctx.stroke()}}
    if(type==='halftone'){for(let y=0;y<h;y+=32*s)for(let x=0;x<w;x+=32*s){const r=(4+12*y/h)*s;ctx.fillStyle=second;ctx.beginPath();ctx.arc(x+(y/32%2)*12,y,r,0,Math.PI*2);ctx.fill()}ctx.fillStyle=accent;ctx.fillRect(0,h*.77,w,h*.06)}
    if(type==='split'){ctx.fillStyle=second;ctx.fillRect(w/2,0,w/2,h);ctx.fillStyle=accent;ctx.fillRect(w/2-8*s,0,16*s,h)}
    if(type==='lightning'){ctx.fillStyle=second;for(let x=-w;x<w*2;x+=220*s){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+150*s,0);ctx.lineTo(x+70*s,h*.46);ctx.lineTo(x+180*s,h*.46);ctx.lineTo(x-20*s,h);ctx.lineTo(x+45*s,h*.55);ctx.lineTo(x-65*s,h*.55);ctx.closePath();ctx.fill()}}
    if(type==='flame'){for(let x=-50;x<w+100;x+=115*s){const g=ctx.createLinearGradient(0,h,0,0);g.addColorStop(0,second);g.addColorStop(.65,accent);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(x,h);ctx.bezierCurveTo(x-50,h*.72,x+80,h*.57,x+20,h*.2);ctx.bezierCurveTo(x+120,h*.55,x+65,h*.78,x+105,h);ctx.fill()}}
    if(type==='topo'){ctx.strokeStyle=second;ctx.lineWidth=4*s;for(let r=35;r<420;r+=38*s){ctx.beginPath();for(let a=0;a<=Math.PI*2+.1;a+=.08){const rr=r+Math.sin(a*5+r)*12*s;ctx.lineTo(w/2+Math.cos(a)*rr,h/2+Math.sin(a)*rr*.7)}ctx.stroke()}ctx.strokeStyle=accent;ctx.lineWidth=8;ctx.strokeRect(w*.1,h*.1,w*.8,h*.8)}
    if(type==='shards'){for(let y=0;y<h;y+=120*s)for(let x=0;x<w;x+=120*s){ctx.fillStyle=(Math.floor(x/120)+Math.floor(y/120))%3?second:accent;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+110*s,y+25*s);ctx.lineTo(x+35*s,y+115*s);ctx.closePath();ctx.fill()}}
    if(type==='pulse'){ctx.strokeStyle=second;ctx.lineWidth=24*s;for(let y=100;y<h;y+=190*s){ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<w;x+=45*s)ctx.lineTo(x,y+(x%180===90?-70:0));ctx.stroke()}ctx.strokeStyle=accent;ctx.lineWidth=6;ctx.stroke()}
    if(type==='camo'){for(let i=0;i<90;i++){const x=(i*83)%w,y=(i*137)%h,r=(28+(i%5)*12)*s;ctx.fillStyle=i%3===0?accent:second;ctx.beginPath();ctx.ellipse(x,y,r,r*.55,(i%7)*.4,0,Math.PI*2);ctx.fill()}}
    if(type==='orbit'){ctx.strokeStyle=second;ctx.lineWidth=22*s;for(let y=80;y<h;y+=190*s){ctx.beginPath();ctx.ellipse(w/2,y,w*.55,70*s,(y%380?-.2:.2),0,Math.PI*2);ctx.stroke()}ctx.strokeStyle=accent;ctx.lineWidth=7*s;ctx.stroke()}
  }

  function drawWrappedImage(img,cx,cy,dw,dh,rotation){for(const dx of [-1024,0,1024]){tctx.save();tctx.translate(cx+dx,cy);tctx.rotate(rotation*Math.PI/180);tctx.drawImage(img,-dw/2,-dh/2,dw,dh);tctx.restore()}}
  function drawTextAndLogos(){
    const frontU=.25,backU=.75,numSize=175*(state.numberSize/100);tctx.save();tctx.textAlign='center';tctx.textBaseline='middle';tctx.lineJoin='round';tctx.fillStyle=state.accent;tctx.strokeStyle=state.secondary;
    const nx=1024*(backU+state.numberX/360),ny=1024*state.numberY/100;tctx.font=`${numSize}px ${state.font}`;
    if(state.numberStyle==='outline'){tctx.lineWidth=11;tctx.strokeText(state.number,nx,ny)}else if(state.numberStyle==='double'){tctx.lineWidth=20;tctx.strokeText(state.number,nx,ny);tctx.strokeStyle=state.base;tctx.lineWidth=8;tctx.strokeText(state.number,nx,ny);tctx.fillText(state.number,nx,ny)}else{tctx.lineWidth=7;tctx.strokeText(state.number,nx,ny);tctx.fillText(state.number,nx,ny)}
    const nameX=1024*(backU+state.nameX/360),nameY=1024*state.nameY/100;tctx.save();tctx.translate(nameX,nameY);tctx.scale(.52,1);tctx.font=`700 ${43*state.nameSize/100}px Arial`;tctx.lineWidth=5;tctx.strokeStyle=state.secondary;tctx.strokeText(state.name,0,0);tctx.fillText(state.name,0,0);tctx.restore();
    tctx.font=`${Math.round(numSize*.48)}px ${state.font}`;tctx.lineWidth=5;tctx.strokeText(state.number,1024*frontU,560);tctx.fillText(state.number,1024*frontU,560);tctx.restore();
    state.logos.forEach(l=>{const img=logoImages.get(l.id);if(!img)return;const size=165*l.size/100,ratio=img.naturalWidth/img.naturalHeight||1,curve=Math.max(.38,Math.cos(Math.min(48,Math.abs(l.x))/48*Math.PI*.38));let dh=size,dw=size*ratio*.5*curve;if(dw>size){dw=size;dh=size/(ratio*.5*curve)}const base=l.side==='back'?backU:frontU;drawWrappedImage(img,1024*(base+l.x/360),1024*l.y/100,dw,dh,l.rotation)})
  }
  function updateTexture(){drawPattern(pctx,512,1024,state.pattern,state.base,state.secondary,state.accent,state.scale/100);tctx.clearRect(0,0,1024,1024);tctx.drawImage(patternCanvas,0,0);tctx.save();tctx.translate(1024,0);tctx.scale(-1,1);tctx.drawImage(patternCanvas,0,0);tctx.restore();const collarFade=tctx.createLinearGradient(0,0,0,135);collarFade.addColorStop(0,state.base);collarFade.addColorStop(.38,state.base+'cc');collarFade.addColorStop(1,state.base+'00');tctx.fillStyle=collarFade;tctx.fillRect(0,0,1024,135);drawTextAndLogos();if(uniformTexture)uniformTexture.needsUpdate=true;updatePatternPreviews()}
  function persistDraft(){try{localStorage.setItem('kitform-design',JSON.stringify(state))}catch(e){}}
  function scheduleTexture(){if(renderPending)return;renderPending=true;requestAnimationFrame(()=>{renderPending=false;updateTexture();persistDraft()})}

  function torsoGeometry(){const ys=28,us=48,verts=[],uv=[],idx=[];for(let iy=0;iy<=ys;iy++){const v=iy/ys,y=-1.65+v*3.3,width=1.28+v*.35+Math.pow(v,8)*.18,depth=.43+v*.03;for(let iu=0;iu<=us;iu++){const u=iu/us,t=-Math.PI/2+u*Math.PI*2;verts.push(Math.sin(t)*width,y,Math.cos(t)*depth);uv.push(u,v)}}for(let y=0;y<ys;y++)for(let x=0;x<us;x++){const a=y*(us+1)+x,b=a+1,c=a+us+1,d=c+1;idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
  function stableUV(source){const g=source.index?source.toNonIndexed():source.clone(),p=g.getAttribute('position'),uv=new Float32Array(p.count*2);let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity,minZ=Infinity,maxZ=-Infinity;for(let i=0;i<p.count;i++){minX=Math.min(minX,p.getX(i));maxX=Math.max(maxX,p.getX(i));minY=Math.min(minY,p.getY(i));maxY=Math.max(maxY,p.getY(i));minZ=Math.min(minZ,p.getZ(i));maxZ=Math.max(maxZ,p.getZ(i))}const midZ=(minZ+maxZ)/2,rx=maxX-minX||1,ry=maxY-minY||1;for(let i=0;i<p.count;i+=3){const front=(p.getZ(i)+p.getZ(i+1)+p.getZ(i+2))/3>=midZ;for(let j=0;j<3;j++){const k=i+j,x=(p.getX(k)-minX)/rx;uv[k*2]=front?x*.5:.5+(1-x)*.5;uv[k*2+1]=(p.getY(k)-minY)/ry}}g.setAttribute('uv',new THREE.BufferAttribute(uv,2));return g}
  function makeSleeve(side,material){const group=new THREE.Group(),mesh=new THREE.Mesh(new THREE.CylinderGeometry(.56,.72,1.42,28,1,true),material);mesh.geometry.rotateZ(side*1.15);mesh.position.set(side*1.83,.95,0);group.add(mesh);return group}
  function addFallback(mat){torso=new THREE.Mesh(torsoGeometry(),mat);jersey.add(torso);sleeves=[makeSleeve(-1,mat),makeSleeve(1,mat)];jersey.add(...sleeves);finishLoad('簡易3Dモデルを読み込みました')}
  function addModel(model,mat){const root=new THREE.Group();root.add(model);model.traverse(o=>{if(!o.isMesh)return;o.geometry=stableUV(o.geometry);o.material=mat;o.castShadow=true;o.receiveShadow=true;torso=o});const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());model.position.sub(center);root.scale.setScalar(3.7/(size.y||1));jersey.add(root);finishLoad('提供された3Dモデルを読み込みました')}
  function finishLoad(message){updateTexture();$('#loading').style.display='none';showToast(message)}
  function makeFabricTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='#808080';x.fillRect(0,0,128,128);x.globalAlpha=.14;for(let i=0;i<128;i+=4){x.strokeStyle=i%8?'#a8a8a8':'#595959';x.beginPath();x.moveTo(0,i);x.lineTo(128,i+18);x.stroke();x.beginPath();x.moveTo(i,0);x.lineTo(i+18,128);x.stroke()}x.globalAlpha=1;const tex=new THREE.CanvasTexture(c);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(42,42);return tex}
  function init3D(){
    if(!window.THREE){$('#loading').textContent='3Dモデルを読み込めませんでした';return}scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(28,1,.1,100);camera.position.set(0,.1,cameraZ);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('#canvasWrap').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0xb9c0b7,2));const key=new THREE.DirectionalLight(0xffffff,3.1);key.position.set(3,4,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;scene.add(key);const rim=new THREE.DirectionalLight(0xd8ffd0,1.1);rim.position.set(-4,1,-4);scene.add(rim);
    uniformTexture=new THREE.CanvasTexture(textureCanvas);uniformTexture.colorSpace=THREE.SRGBColorSpace;uniformTexture.wrapS=THREE.ClampToEdgeWrapping;const mat=new THREE.MeshPhysicalMaterial({map:uniformTexture,bumpMap:makeFabricTexture(),bumpScale:.012,roughness:.84,metalness:0,sheen:.18,sheenColor:new THREE.Color(0xffffff),sheenRoughness:.9,clearcoat:.025,clearcoatRoughness:.92,side:THREE.DoubleSide});jersey=new THREE.Group();jersey.rotation.y=targetRotY;scene.add(jersey);const shadow=new THREE.Mesh(new THREE.CircleGeometry(2.4,48),new THREE.ShadowMaterial({color:0x182018,transparent:true,opacity:.15}));shadow.scale.y=.28;shadow.rotation.x=-Math.PI/2;shadow.position.y=-2.05;shadow.receiveShadow=true;scene.add(shadow);
    const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;targetRotY+=(e.clientX-lastX)*.01;targetRotX=Math.max(-1.25,Math.min(1.25,targetRotX+(e.clientY-lastY)*.008));lastX=e.clientX;lastY=e.clientY});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(cameraZ+e.deltaY*.006)},{passive:false});window.addEventListener('resize',resize);resize();animate();
    if(window.GLTFLoader)new GLTFLoader().load('assets/uniform.glb',g=>addModel(g.scene,mat),undefined,()=>addFallback(mat));else addFallback(mat)
  }
  function resize(){if(!renderer)return;const el=$('#canvasWrap');renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()}
  function animate(){requestAnimationFrame(animate);if(state.autoRotate&&!drag)targetRotY+=.006;jersey.rotation.y+=(targetRotY-jersey.rotation.y)*.085;jersey.rotation.x+=(targetRotX-jersey.rotation.x)*.085;renderer.render(scene,camera)}
  function setZoom(z){cameraZ=Math.max(7,Math.min(12,z));camera.position.z=cameraZ}
  function updateMaterials(){updateTexture()}

  function createPatterns(){Object.entries(patternNames).forEach(([id,name])=>{const b=document.createElement('button');b.className='pattern-card'+(id===state.pattern?' active':'');b.dataset.pattern=id;b.innerHTML=`<canvas width="180" height="180" data-pattern="${id}"></canvas><b>${name}</b>`;b.onclick=()=>{state.pattern=id;$$('.pattern-card').forEach(x=>x.classList.toggle('active',x===b));scheduleTexture()};$('#patternGrid').appendChild(b)});updatePatternPreviews()}
  function updatePatternPreviews(){$$('.pattern-card canvas').forEach(c=>drawPattern(c.getContext('2d'),c.width,c.height,c.dataset.pattern,state.base,state.secondary,state.accent,.55))}
  function activeLogo(){return state.logos.find(l=>l.id===state.activeLogoId)}
  function selectLogo(id){state.activeLogoId=id;renderLogoSlots();syncLogoControls();scheduleTexture()}
  function renderLogoSlots(){const box=$('#logoSlots');box.innerHTML='';if(!state.logos.length){box.innerHTML='<span>ロゴはまだありません</span>';return}state.logos.forEach((l,i)=>{const b=document.createElement('button');b.className='logo-slot'+(l.id===state.activeLogoId?' active':'');b.textContent=`LOGO ${i+1}`;b.onclick=()=>selectLogo(l.id);box.appendChild(b)})}
  function syncLogoControls(){const l=activeLogo(),controls=$('#logoControls');controls.classList.toggle('disabled',!l);if(!l)return;$('#logoSize').value=l.size;$('#logoX').value=l.x;$('#logoY').value=l.y;$('#logoRotation').value=l.rotation;$('#logoSide').value=l.side;updateRangeOutputs()}
  function addLogo(data,name){if(state.logos.length>=6){showToast('ロゴは最大6個までです');return}const id=Date.now()+Math.random(),logo={id,name,size:100,x:0,y:38,rotation:0,side:'front',data};state.logos.push(logo);const img=new Image();img.onload=()=>{logoImages.set(id,img);selectLogo(id);showToast(`LOGO ${state.logos.length} を追加しました`)};img.src=data}
  function hydrateLogoImages(){state.logos.forEach(l=>{const img=new Image();img.onload=()=>{logoImages.set(l.id,img);scheduleTexture()};img.src=l.data})}
  function updateRangeOutputs(){$$('input[type=range]').forEach(r=>{const out=$('#'+r.id+'Value');if(!out)return;if(r.id==='logoRotation')out.textContent=`${r.value}°`;else if(['logoX','nameX','numberX'].includes(r.id))out.textContent=+r.value===0?'中央':`${+r.value<0?'左':'右'} ${Math.abs(r.value)}%`;else out.textContent=`${r.value}%`})}
  function hydrateUI(){const map={patternScale:'scale',playerName:'name',nameSize:'nameSize',playerNumber:'number',numberFont:'font',numberStyle:'numberStyle',numberSize:'numberSize',nameX:'nameX',nameY:'nameY',numberX:'numberX',numberY:'numberY'};Object.entries(map).forEach(([id,k])=>{if($('#'+id))$('#'+id).value=state[k]});[['baseColor','base'],['secondaryColor','secondary'],['accentColor','accent']].forEach(([id,k])=>{$('#'+id).value=state[k];$('#'+id).closest('label').querySelector('code').textContent=state[k].toUpperCase()});$('#autoRotate').classList.toggle('active',state.autoRotate);$('#autoRotate').textContent=state.autoRotate?'STOP':'AUTO';renderLogoSlots();syncLogoControls();updateRangeOutputs()}

  function saveCollection(){if(!renderer)return;const thumb=document.createElement('canvas');thumb.width=320;thumb.height=240;const tc=thumb.getContext('2d');tc.fillStyle='#f3f5f1';tc.fillRect(0,0,320,240);tc.drawImage(renderer.domElement,0,0,320,240);const items=getCollection();items.unshift({id:Date.now(),created:new Date().toLocaleString('ja-JP'),preview:thumb.toDataURL('image/jpeg',.72),state:JSON.parse(JSON.stringify(state))});try{localStorage.setItem('kitform-designs',JSON.stringify(items.slice(0,12)));localStorage.setItem('kitform-design',JSON.stringify(state));showToast('マイコレクションに保存しました');renderCollection()}catch(e){showToast('保存容量を超えました。古いデザインを削除してください')}}
  function getCollection(){try{return JSON.parse(localStorage.getItem('kitform-designs'))||[]}catch(e){return[]}}
  function renderCollection(){const grid=$('#savedGrid'),items=getCollection();grid.innerHTML='';if(!items.length){grid.innerHTML='<div class="saved-empty">保存したユニフォームはまだありません。<br>「デザイン保存」から追加できます。</div>';return}items.forEach((item,i)=>{const card=document.createElement('article');card.className='saved-card';card.innerHTML=`<img src="${item.preview}" alt="保存デザイン ${i+1}"><div class="saved-card-body"><b>DESIGN ${String(items.length-i).padStart(2,'0')}</b><small>${item.created}</small><div class="saved-card-actions"><button class="load">読み込む</button><button class="delete">削除</button></div></div>`;card.querySelector('.load').onclick=()=>{localStorage.setItem('kitform-design',JSON.stringify(item.state));location.reload()};card.querySelector('.delete').onclick=()=>{localStorage.setItem('kitform-designs',JSON.stringify(items.filter(x=>x.id!==item.id)));renderCollection()};grid.appendChild(card)})}
  function openGallery(open=true){$('#galleryModal').classList.toggle('open',open);$('#galleryModal').setAttribute('aria-hidden',String(!open));if(open)renderCollection()}

  function openAR(open=true){$('#arModal').classList.toggle('open',open);$('#arModal').setAttribute('aria-hidden',String(!open));if(open)updateSizeRecommendation(lastPoseLandmarks);else stopAR()}
  function loadExternalScript(src){return new Promise((resolve,reject)=>{if(window.Pose)return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  function point(lm,i,w,h){return{x:lm[i].x*w,y:lm[i].y*h,v:lm[i].visibility??1}}
  function drawARTryOn(results){
    const video=$('#arVideo'),canvas=$('#arCanvas');if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const lm=results.poseLandmarks;if(!lm||[11,12,23,24].some(i=>(lm[i].visibility??0)<.45))return;
    lastPoseLandmarks=lm;updateSizeRecommendation(lm);const ls=point(lm,11,w,h),rs=point(lm,12,w,h),lh=point(lm,23,w,h),rh=point(lm,24,w,h),le=point(lm,13,w,h),re=point(lm,14,w,h);const sw=Math.hypot(rs.x-ls.x,rs.y-ls.y),topY=(ls.y+rs.y)/2-sw*.12,bottomY=(lh.y+rh.y)/2+sw*.12,cx=(ls.x+rs.x+lh.x+rh.x)/4,leftShoulderX=ls.x-(rs.x-ls.x)*.12,rightShoulderX=rs.x+(rs.x-ls.x)*.12,leftSleeveX=ls.x+(le.x-ls.x)*.55-sw*.12,rightSleeveX=rs.x+(re.x-rs.x)*.55+sw*.12,leftHipX=lh.x-sw*.08,rightHipX=rh.x+sw*.08;
    ctx.save();ctx.beginPath();ctx.moveTo(cx-sw*.13,topY);ctx.quadraticCurveTo(cx,(ls.y+rs.y)/2+sw*.08,cx+sw*.13,topY);ctx.lineTo(rightShoulderX,rs.y);ctx.lineTo(rightSleeveX,rs.y+(re.y-rs.y)*.5);ctx.lineTo(rs.x+sw*.12,rs.y+sw*.3);ctx.lineTo(rightHipX,bottomY);ctx.lineTo(leftHipX,bottomY);ctx.lineTo(ls.x-sw*.12,ls.y+sw*.3);ctx.lineTo(leftSleeveX,ls.y+(le.y-ls.y)*.5);ctx.lineTo(leftShoulderX,ls.y);ctx.closePath();ctx.clip();ctx.globalAlpha=.91;const minX=Math.min(leftSleeveX,leftHipX),maxX=Math.max(rightSleeveX,rightHipX);ctx.drawImage(patternCanvas,minX,topY,maxX-minX,bottomY-topY);const shade=ctx.createLinearGradient(minX,0,maxX,0);shade.addColorStop(0,'rgba(0,0,0,.2)');shade.addColorStop(.22,'rgba(255,255,255,.04)');shade.addColorStop(.78,'rgba(255,255,255,.04)');shade.addColorStop(1,'rgba(0,0,0,.2)');ctx.fillStyle=shade;ctx.fillRect(minX,topY,maxX-minX,bottomY-topY);ctx.restore();
    ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${Math.max(18,sw*.13)}px ${state.font}`;ctx.lineWidth=Math.max(2,sw*.008);ctx.strokeStyle=state.secondary;ctx.fillStyle=state.accent;ctx.strokeText(state.number,cx,topY+(bottomY-topY)*.56);ctx.fillText(state.number,cx,topY+(bottomY-topY)*.56);ctx.restore();
    state.logos.filter(l=>l.side==='front').forEach(l=>{const img=logoImages.get(l.id);if(!img)return;const ratio=img.naturalWidth/img.naturalHeight||1,size=sw*.22*l.size/100;let dw=size,dh=size/ratio;if(dh>size){dh=size;dw=size*ratio}const x=cx+(l.x/100)*sw,y=topY+(l.y/100)*(bottomY-topY);ctx.save();ctx.translate(x,y);ctx.rotate(l.rotation*Math.PI/180);ctx.drawImage(img,-dw/2,-dh/2,dw,dh);ctx.restore()})
  }
  function updateSizeRecommendation(lm){const height=Math.max(130,Math.min(210,+$('#bodyHeight').value||170)),manualChest=+$('#bodyChest').value||0,fit=$('#fitPreference').value,sizes=['S','M','L','XL','2XL'];let shoulderCm=null,chest=manualChest;if(lm){const sw=Math.hypot(lm[12].x-lm[11].x,lm[12].y-lm[11].y),smx=(lm[11].x+lm[12].x)/2,smy=(lm[11].y+lm[12].y)/2,hmx=(lm[23].x+lm[24].x)/2,hmy=(lm[23].y+lm[24].y)/2,torso=Math.hypot(hmx-smx,hmy-smy);shoulderCm=Math.max(34,Math.min(58,height*.29*(sw/(torso||.25))));if(!chest)chest=shoulderCm*2.08}let hi=height<165?0:height<173?1:height<181?2:height<189?3:4,ci=chest?(chest<88?0:chest<96?1:chest<104?2:chest<114?3:4):hi,idx=Math.max(hi,ci);if(fit==='loose')idx++;if(fit==='slim')idx--;idx=Math.max(0,Math.min(4,idx));$('#sizeResult strong').textContent=sizes[idx];const details=[];if(shoulderCm)details.push(`推定肩幅 約${shoulderCm.toFixed(1)}cm`);if(chest)details.push(`${manualChest?'入力':'推定'}胸囲 約${chest.toFixed(0)}cm`);details.push('サイズは目安です');$('#sizeResult small').textContent=details.join(' · ')}
  function cameraErrorMessage(e){
    if(!window.isSecureContext)return 'カメラはHTTPSで開いたページからのみ使用できます';
    if(e?.name==='NotAllowedError'||e?.name==='PermissionDeniedError')return 'カメラが許可されていません。Safariの「設定 → Webサイト → カメラ」でこのサイトを許可してください';
    if(e?.name==='NotFoundError'||e?.name==='DevicesNotFoundError')return '利用できるカメラが見つかりません。カメラの接続を確認してください';
    if(e?.name==='NotReadableError'||e?.name==='TrackStartError')return 'カメラをほかのアプリが使用中です。FaceTimeやZoomを閉じて再試行してください';
    return e?.message||'カメラの許可と接続を確認してください';
  }
  function updateCameraUI(){
    const rear=arFacing==='environment',stage=$('#arStage'),status=$('#cameraStatus');
    stage?.classList.toggle('rear-camera',rear);
    if(status)status.textContent=`${rear?'外側':'内側'}カメラを使用中`;
  }
  async function startAR(){
    if(arRunning)return;const empty=$('#arEmpty'),video=$('#arVideo');
    try{
      if(!navigator.mediaDevices?.getUserMedia)throw new Error('このブラウザはカメラに対応していません');
      empty.style.display='flex';empty.innerHTML='<b>カメラを準備しています…</b><span>許可ダイアログでカメラを許可してください</span>';
      arStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:arFacing},width:{ideal:1920},height:{ideal:1080}},audio:false});
      video.srcObject=arStream;video.setAttribute('autoplay','');await video.play();
      arRunning=true;updateCameraUI();empty.style.display='none';$('#startAR').disabled=true;$('#stopAR').disabled=false;$('#switchCamera').disabled=false;
      try{
        await loadExternalScript('https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1675469404/pose.js');
        if(!arPose){arPose=new window.Pose({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1675469404/${f}`});arPose.setOptions({modelComplexity:1,smoothLandmarks:true,enableSegmentation:false,minDetectionConfidence:.5,minTrackingConfidence:.5});arPose.onResults(drawARTryOn)}
        const tick=async()=>{if(!arRunning)return;if(!arBusy){arBusy=true;try{await arPose.send({image:video})}catch(e){console.warn('Pose detection:',e)}finally{arBusy=false}}arTimer=setTimeout(tick,66)};tick();
      }catch(e){$('#cameraStatus').textContent='カメラ映像は表示中です（姿勢検出を読み込めませんでした）';console.warn('Pose setup:',e)}
    }catch(e){empty.style.display='flex';empty.innerHTML=`<b>カメラを開始できませんでした</b><span>${cameraErrorMessage(e)}</span>`;stopAR(false)}
  }
  async function switchCamera(){
    const wasRunning=arRunning;stopAR(false);arFacing=arFacing==='user'?'environment':'user';updateCameraUI();if(wasRunning)await startAR();
  }
  function stopAR(resetMessage=true){arRunning=false;arBusy=false;clearTimeout(arTimer);arTimer=null;if(arStream){arStream.getTracks().forEach(t=>t.stop());arStream=null}const video=$('#arVideo');if(video)video.srcObject=null;const canvas=$('#arCanvas');if(canvas)canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);if($('#startAR'))$('#startAR').disabled=false;if($('#stopAR'))$('#stopAR').disabled=true;if($('#switchCamera'))$('#switchCamera').disabled=true;if(resetMessage&&$('#arEmpty')){$('#arEmpty').style.display='flex';$('#arEmpty').innerHTML='<b>カメラでユニフォームを試着</b><span>上半身全体が映る位置に立ってください</span>'}}

  function bindUI(){
    $$('.tab').forEach(tab=>tab.onclick=()=>{state.autoRotate=false;$('#autoRotate').classList.remove('active');$('#autoRotate').textContent='AUTO';persistDraft();$$('.tab').forEach(x=>x.classList.toggle('active',x===tab));$$('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===tab.dataset.tab))});
    const bind=(id,key,fn=v=>v)=>$('#'+id).addEventListener('input',e=>{state[key]=fn(e.target.value);scheduleTexture()});['patternScale','nameSize','numberSize','nameX','nameY','numberX','numberY'].forEach(id=>bind(id,{patternScale:'scale',nameSize:'nameSize',numberSize:'numberSize',nameX:'nameX',nameY:'nameY',numberX:'numberX',numberY:'numberY'}[id],Number));bind('playerName','name');bind('playerNumber','number');bind('numberFont','font');bind('numberStyle','numberStyle');
    [['baseColor','base'],['secondaryColor','secondary'],['accentColor','accent']].forEach(([id,key])=>$('#'+id).oninput=e=>{state[key]=e.target.value;e.target.closest('label').querySelector('code').textContent=e.target.value.toUpperCase();updateMaterials()});
    $$('input[type=range]').forEach(r=>r.addEventListener('input',updateRangeOutputs));
    ['logoSize','logoX','logoY','logoRotation'].forEach(id=>$('#'+id).oninput=e=>{const l=activeLogo();if(!l)return;l[{logoSize:'size',logoX:'x',logoY:'y',logoRotation:'rotation'}[id]]=+e.target.value;scheduleTexture()});$('#logoSide').onchange=e=>{const l=activeLogo();if(l){l.side=e.target.value;scheduleTexture()}};
    $('#logoUpload').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>5e6){showToast('5MB以下の画像を選択してください');return}const reader=new FileReader();reader.onload=()=>addLogo(reader.result,f.name);reader.readAsDataURL(f);e.target.value=''};$('#removeLogo').onclick=()=>{const id=state.activeLogoId,index=state.logos.findIndex(l=>l.id===id);if(index<0)return;state.logos.splice(index,1);logoImages.delete(id);state.activeLogoId=state.logos[Math.max(0,index-1)]?.id||null;renderLogoSlots();syncLogoControls();scheduleTexture()};
    $$('.view-controls [data-view]').forEach(b=>b.onclick=()=>{$$('.view-controls [data-view]').forEach(x=>x.classList.toggle('active',x===b));const v=b.dataset.view;if(v==='front'||v==='back'||v==='side'){targetRotX=0;targetRotY={front:0,back:Math.PI,side:Math.PI/2}[v]}else{targetRotX=v==='top'?1.15:-1.15}});$('#autoRotate').onclick=e=>{state.autoRotate=!state.autoRotate;e.currentTarget.classList.toggle('active',state.autoRotate);e.currentTarget.textContent=state.autoRotate?'STOP':'AUTO';persistDraft()};$('#zoomIn').onclick=()=>setZoom(cameraZ-.55);$('#zoomOut').onclick=()=>setZoom(cameraZ+.55);
    $('#shuffleColors').onclick=()=>{const p=palettes[Math.floor(Math.random()*palettes.length)];[['baseColor','base'],['secondaryColor','secondary'],['accentColor','accent']].forEach(([id,k],i)=>{$('#'+id).value=p[i];state[k]=p[i];$('#'+id).closest('label').querySelector('code').textContent=p[i].toUpperCase()});updateMaterials()};$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.download='kitform-uniform.png';a.href=renderer.domElement.toDataURL('image/png');a.click();showToast('PNG画像を書き出しました')};
    $('#saveBtn').onclick=saveCollection;$('#galleryBtn').onclick=()=>openGallery(true);$('#closeGallery').onclick=()=>openGallery(false);$('#galleryModal').onclick=e=>{if(e.target===$('#galleryModal'))openGallery(false)};$('#arBtn').onclick=()=>{openAR(true);startAR()};$('#closeAR').onclick=()=>openAR(false);$('#arModal').onclick=e=>{if(e.target===$('#arModal'))openAR(false)};$('#startAR').onclick=startAR;$('#switchCamera').onclick=switchCamera;$('#stopAR').onclick=()=>stopAR();['bodyHeight','bodyChest','fitPreference'].forEach(id=>$('#'+id).addEventListener('input',()=>updateSizeRecommendation(lastPoseLandmarks)));$('#undoBtn').onclick=()=>showToast('各項目はいつでも再調整できます');$('#resetBtn').onclick=()=>{if(!confirm('現在の編集内容を初期状態に戻しますか？\n保存済みコレクションは削除されません。'))return;localStorage.removeItem('kitform-design');location.reload()};
  }
  function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2500)}
  function loadSaved(){try{const s=JSON.parse(localStorage.getItem('kitform-design'));if(s)state={...DEFAULTS,...s,logos:Array.isArray(s.logos)?s.logos:[],autoRotate:false}}catch(e){}}
  loadSaved();hydrateLogoImages();createPatterns();hydrateUI();bindUI();init3D();
})();
